
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    // AutoGenerated File

export enum ConnectionTypeEnum {
    Wifi = 1,
    NRF24L01 = 2,
    I2C = 3
}
