
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    
    export interface DeviceTrait {
        /**  [Type:string] */
        deviceTraitId?: string;
        /**  [Type:string] */
        displayName?: string;
        /**  [Type:string] */
        description?: string;
    }
    
