
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { DeviceTrait } from './DeviceTrait';

    export interface DeviceType {
        deviceTypeId?: string;
        displayName?: string;
        description?: string;
        recommendedTraits?: DeviceTrait[];
    }
    
