
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { DeviceType } from './DeviceType';
import { DeviceTrait } from './DeviceTrait';
import { DeviceNickName } from './DeviceNickName';
import { Hub } from './Hub';
import { Relay } from './Relay';
import { Piece } from './Piece';

    export interface Device {
        deviceId/*Required*/: string;
        userId?: string;
        relayId?: string;
        hubId/*Required*/: string;
        pieceId/*Required*/: string;
        name/*Required*/: string;
        arduinoId/*Required*/: number;
        deviceType?: DeviceType;
        traits?: DeviceTrait[];
        nickNames?: DeviceNickName[];
        hub?: Hub;
        relay?: Relay;
        piece?: Piece;
    }
    
