
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { DeviceTrait } from './DeviceTrait';

    export interface DeviceType {
        /**  [Type:string] */
        deviceTypeId?: string;
        /**  [Type:string] */
        displayName?: string;
        /**  [Type:string] */
        description?: string;
        /**  [Type:DeviceTrait[]] */
        recommendedTraits?: DeviceTrait[];
    }
    
