
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    
    export interface DeviceNickName {
        deviceNickNameId/*Required*/: string;
        deviceId/*Required*/: string;
        nickName?: string;
    }
    
