
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    
    export interface GoogleUser {
        googleUserId/*Required*/: string;
        userId?: string;
        active/*Required*/: boolean;
        activationDate/*Required*/: Date;
    }
    
