
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Hub } from './Hub';
import { Piece } from './Piece';

    export interface Home {
        HomeId: string;
        UserId: string;
        Name: string;
        FullAddress: string;
        City: string;
        State: string;
        Country: string;
        Hubs: Hub[];
        Pieces: Piece[];
    }
    
