
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Hub } from './Hub';
import { Piece } from './Piece';

    export interface Home {
        homeId?: string;
        userId?: string;
        name/*Required*/: string;
        fullAddress/*Required*/: string;
        city/*Required*/: string;
        state/*Required*/: string;
        country/*Required*/: string;
        hubs?: Hub[];
        pieces?: Piece[];
    }
    
