
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    
    export interface Home {
        /** Db Key [Type:Guid] */
        homeId?: string;
        /** UserId Guid. Will be overwrited on Insert and Update by the current userid [Type:string] */
        userId?: string;
        /** Home Name. In case you control more than one home. [Type:string] */
        name/*Required*/: string;
        /** Full Street address used to get whether and others informations to the Hub [Type:string] */
        fullAddress/*Required*/: string;
        /** City used to get whether and others informations to the Hub [Type:string] */
        city/*Required*/: string;
        /** State used to get whether and others informations to the Hub [Type:string] */
        state/*Required*/: string;
        /** Country used to get whether and others informations to the Hub [Type:string] */
        country/*Required*/: string;
    }
    
