
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Piece } from './Piece';
import { Device } from './Device';
import { Relay } from './Relay';

    export interface Hub {
        hubId/*Required*/: string;
        userId/*Required*/: string;
        homeId/*Required*/: string;
        hardware?: string;
        pieceId/*Required*/: string;
        piece?: Piece;
        devices?: Device[];
        relays?: Relay[];
    }
    
