
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    
    export interface MyAngularConfig {
        /**  [Type:string] */
        clientId?: string;
        /**  [Type:string] */
        authServer?: string;
        /**  [Type:string] */
        scope?: string;
        /**  [Type:string] */
        apiServer?: string;
        /**  [Type:string] */
        websiteName?: string;
        /**  [Type:string] */
        websiteShortName?: string;
    }
    
