
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    // AutoGenerated File

export enum PieceTypeEnum {
    Kitchen = 1,
    Master_Bedroom = 2,
    Bedroom = 3,
    Living_Room = 4,
    BathRoom = 5
}
