
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Home } from './Home';
import { PieceTypeEnum } from './PieceTypeEnum';

    export interface Piece {
        PieceId: string;
        HomeId: string;
        Home: Home;
        UserId: string;
        Name: string;
        Type: PieceTypeEnum;
        Floor: number;
    }
    
