
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Home } from './Home';
import { PieceTypeEnum } from './PieceTypeEnum';

    export interface Piece {
        pieceId?: string;
        homeId/*Required*/: string;
        home?: Home;
        userId?: string;
        name/*Required*/: string;
        type/*Required*/: PieceTypeEnum;
        floor/*Required*/: number;
    }
    
