
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Hub } from './Hub';
import { ConnectionTypeEnum } from './ConnectionTypeEnum';

    export interface Relay {
        RelayId: string;
        HubId: string;
        Hub: Hub;
        UserId: string;
        Name: string;
        HardWare: string;
        ConnectionType: ConnectionTypeEnum;
    }
    
