
    // This File was auto-generated by TypeWriter. Any changes can be overriten if regenerated.
    // To modify this class, edit "1_ApiModels"
    // More info: http://frhagn.github.io/Typewriter/
    import { Hub } from './Hub';
import { ConnectionTypeEnum } from './ConnectionTypeEnum';

    export interface Relay {
        relayId/*Required*/: string;
        hubId/*Required*/: string;
        hub?: Hub;
        userId/*Required*/: string;
        name/*Required*/: string;
        hardWare?: string;
        connectionType/*Required*/: ConnectionTypeEnum;
    }
    
