//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Web.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeZones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeZones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST.Web.Service.TimeZones", typeof(TimeZones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:30) Kabul.
        /// </summary>
        public static string Afghanistan_Standard_Time {
            get {
                return ResourceManager.GetString("Afghanistan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-09:00) Alaska.
        /// </summary>
        public static string Alaskan_Standard_Time {
            get {
                return ResourceManager.GetString("Alaskan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Kuwait, Riyadh.
        /// </summary>
        public static string Arab_Standard_Time {
            get {
                return ResourceManager.GetString("Arab_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Abu Dhabi, Muscat.
        /// </summary>
        public static string Arabian_Standard_Time {
            get {
                return ResourceManager.GetString("Arabian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Baghdad.
        /// </summary>
        public static string Arabic_Standard_Time {
            get {
                return ResourceManager.GetString("Arabic_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Buenos Aires.
        /// </summary>
        public static string Argentina_Standard_Time {
            get {
                return ResourceManager.GetString("Argentina_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Atlantic Time (Canada).
        /// </summary>
        public static string Atlantic_Standard_Time {
            get {
                return ResourceManager.GetString("Atlantic_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Darwin.
        /// </summary>
        public static string AUS_Central_Standard_Time {
            get {
                return ResourceManager.GetString("AUS_Central_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Canberra, Melbourne, Sydney.
        /// </summary>
        public static string AUS_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("AUS_Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Baku.
        /// </summary>
        public static string Azerbaijan_Standard_Time {
            get {
                return ResourceManager.GetString("Azerbaijan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Azores.
        /// </summary>
        public static string Azores_Standard_Time {
            get {
                return ResourceManager.GetString("Azores_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Salvador.
        /// </summary>
        public static string Bahia_Standard_Time {
            get {
                return ResourceManager.GetString("Bahia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Dhaka.
        /// </summary>
        public static string Bangladesh_Standard_Time {
            get {
                return ResourceManager.GetString("Bangladesh_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Minsk.
        /// </summary>
        public static string Belarus_Standard_Time {
            get {
                return ResourceManager.GetString("Belarus_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Saskatchewan.
        /// </summary>
        public static string Canada_Central_Standard_Time {
            get {
                return ResourceManager.GetString("Canada_Central_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-01:00) Cape Verde Is..
        /// </summary>
        public static string Cape_Verde_Standard_Time {
            get {
                return ResourceManager.GetString("Cape_Verde_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Yerevan.
        /// </summary>
        public static string Caucasus_Standard_Time {
            get {
                return ResourceManager.GetString("Caucasus_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:30) Adelaide.
        /// </summary>
        public static string Cen_Australia_Standard_Time {
            get {
                return ResourceManager.GetString("Cen_Australia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Central America.
        /// </summary>
        public static string Central_America_Standard_Time {
            get {
                return ResourceManager.GetString("Central_America_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Astana.
        /// </summary>
        public static string Central_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Cuiaba.
        /// </summary>
        public static string Central_Brazilian_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Brazilian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague.
        /// </summary>
        public static string Central_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Europe_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb.
        /// </summary>
        public static string Central_European_Standard_Time {
            get {
                return ResourceManager.GetString("Central_European_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Solomon Is., New Caledonia.
        /// </summary>
        public static string Central_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Central Time (US &amp; Canada).
        /// </summary>
        public static string Central_Standard_Time {
            get {
                return ResourceManager.GetString("Central_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-06:00) Guadalajara, Mexico City, Monterrey.
        /// </summary>
        public static string Central_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Central_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi.
        /// </summary>
        public static string China_Standard_Time {
            get {
                return ResourceManager.GetString("China_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-12:00) International Date Line West.
        /// </summary>
        public static string Dateline_Standard_Time {
            get {
                return ResourceManager.GetString("Dateline_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Nairobi.
        /// </summary>
        public static string E_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("E_Africa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Brisbane.
        /// </summary>
        public static string E_Australia_Standard_Time {
            get {
                return ResourceManager.GetString("E_Australia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) E. Europe.
        /// </summary>
        public static string E_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("E_Europe_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Brasilia.
        /// </summary>
        public static string E_South_America_Standard_Time {
            get {
                return ResourceManager.GetString("E_South_America_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        public static string Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Cairo.
        /// </summary>
        public static string Egypt_Standard_Time {
            get {
                return ResourceManager.GetString("Egypt_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ekaterinburg (RTZ 4).
        /// </summary>
        public static string Ekaterinburg_Standard_Time {
            get {
                return ResourceManager.GetString("Ekaterinburg_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Fiji.
        /// </summary>
        public static string Fiji_Standard_Time {
            get {
                return ResourceManager.GetString("Fiji_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius.
        /// </summary>
        public static string FLE_Standard_Time {
            get {
                return ResourceManager.GetString("FLE_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Tbilisi.
        /// </summary>
        public static string Georgian_Standard_Time {
            get {
                return ResourceManager.GetString("Georgian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Dublin, Edinburgh, Lisbon, London.
        /// </summary>
        public static string GMT_Standard_Time {
            get {
                return ResourceManager.GetString("GMT_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Greenland.
        /// </summary>
        public static string Greenland_Standard_Time {
            get {
                return ResourceManager.GetString("Greenland_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Monrovia, Reykjavik.
        /// </summary>
        public static string Greenwich_Standard_Time {
            get {
                return ResourceManager.GetString("Greenwich_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Athens, Bucharest.
        /// </summary>
        public static string GTB_Standard_Time {
            get {
                return ResourceManager.GetString("GTB_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-10:00) Hawaii.
        /// </summary>
        public static string Hawaiian_Standard_Time {
            get {
                return ResourceManager.GetString("Hawaiian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi.
        /// </summary>
        public static string India_Standard_Time {
            get {
                return ResourceManager.GetString("India_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:30) Tehran.
        /// </summary>
        public static string Iran_Standard_Time {
            get {
                return ResourceManager.GetString("Iran_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Jerusalem.
        /// </summary>
        public static string Israel_Standard_Time {
            get {
                return ResourceManager.GetString("Israel_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Amman.
        /// </summary>
        public static string Jordan_Standard_Time {
            get {
                return ResourceManager.GetString("Jordan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Kaliningrad (RTZ 1).
        /// </summary>
        public static string Kaliningrad_Standard_Time {
            get {
                return ResourceManager.GetString("Kaliningrad_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Petropavlovsk-Kamchatsky - Old.
        /// </summary>
        public static string Kamchatka_Standard_Time {
            get {
                return ResourceManager.GetString("Kamchatka_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Seoul.
        /// </summary>
        public static string Korea_Standard_Time {
            get {
                return ResourceManager.GetString("Korea_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Tripoli.
        /// </summary>
        public static string Libya_Standard_Time {
            get {
                return ResourceManager.GetString("Libya_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+14:00) Kiritimati Island.
        /// </summary>
        public static string Line_Islands_Standard_Time {
            get {
                return ResourceManager.GetString("Line_Islands_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Magadan.
        /// </summary>
        public static string Magadan_Standard_Time {
            get {
                return ResourceManager.GetString("Magadan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Port Louis.
        /// </summary>
        public static string Mauritius_Standard_Time {
            get {
                return ResourceManager.GetString("Mauritius_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Mid-Atlantic - Old.
        /// </summary>
        public static string MidAtlantic_Standard_Time {
            get {
                return ResourceManager.GetString("MidAtlantic_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Beirut.
        /// </summary>
        public static string Middle_East_Standard_Time {
            get {
                return ResourceManager.GetString("Middle_East_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Montevideo.
        /// </summary>
        public static string Montevideo_Standard_Time {
            get {
                return ResourceManager.GetString("Montevideo_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Casablanca.
        /// </summary>
        public static string Morocco_Standard_Time {
            get {
                return ResourceManager.GetString("Morocco_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Mountain Time (US &amp; Canada).
        /// </summary>
        public static string Mountain_Standard_Time {
            get {
                return ResourceManager.GetString("Mountain_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Chihuahua, La Paz, Mazatlan.
        /// </summary>
        public static string Mountain_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Mountain_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:30) Yangon (Rangoon).
        /// </summary>
        public static string Myanmar_Standard_Time {
            get {
                return ResourceManager.GetString("Myanmar_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+06:00) Novosibirsk (RTZ 5).
        /// </summary>
        public static string N_Central_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("N_Central_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Windhoek.
        /// </summary>
        public static string Namibia_Standard_Time {
            get {
                return ResourceManager.GetString("Namibia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:45) Kathmandu.
        /// </summary>
        public static string Nepal_Standard_Time {
            get {
                return ResourceManager.GetString("Nepal_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Auckland, Wellington.
        /// </summary>
        public static string New_Zealand_Standard_Time {
            get {
                return ResourceManager.GetString("New_Zealand_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:30) Newfoundland.
        /// </summary>
        public static string Newfoundland_Standard_Time {
            get {
                return ResourceManager.GetString("Newfoundland_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Irkutsk (RTZ 7).
        /// </summary>
        public static string North_Asia_East_Standard_Time {
            get {
                return ResourceManager.GetString("North_Asia_East_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Krasnoyarsk (RTZ 6).
        /// </summary>
        public static string North_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("North_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Santiago.
        /// </summary>
        public static string Pacific_SA_Standard_Time {
            get {
                return ResourceManager.GetString("Pacific_SA_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Pacific Time (US &amp; Canada).
        /// </summary>
        public static string Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-08:00) Baja California.
        /// </summary>
        public static string Pacific_Standard_Time_Mexico {
            get {
                return ResourceManager.GetString("Pacific_Standard_Time_Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Islamabad, Karachi.
        /// </summary>
        public static string Pakistan_Standard_Time {
            get {
                return ResourceManager.GetString("Pakistan_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Asuncion.
        /// </summary>
        public static string Paraguay_Standard_Time {
            get {
                return ResourceManager.GetString("Paraguay_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        public static string Romance_Standard_Time {
            get {
                return ResourceManager.GetString("Romance_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+11:00) Chokurdakh (RTZ 10).
        /// </summary>
        public static string Russia_Time_Zone_10 {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky (RTZ 11).
        /// </summary>
        public static string Russia_Time_Zone_11 {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+04:00) Izhevsk, Samara (RTZ 3).
        /// </summary>
        public static string Russia_Time_Zone_3 {
            get {
                return ResourceManager.GetString("Russia_Time_Zone_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+03:00) Moscow, St. Petersburg, Volgograd (RTZ 2).
        /// </summary>
        public static string Russian_Standard_Time {
            get {
                return ResourceManager.GetString("Russian_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-03:00) Cayenne, Fortaleza.
        /// </summary>
        public static string SA_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("SA_Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Bogota, Lima, Quito, Rio Branco.
        /// </summary>
        public static string SA_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("SA_Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:00) Georgetown, La Paz, Manaus, San Juan.
        /// </summary>
        public static string SA_Western_Standard_Time {
            get {
                return ResourceManager.GetString("SA_Western_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Samoa.
        /// </summary>
        public static string Samoa_Standard_Time {
            get {
                return ResourceManager.GetString("Samoa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+07:00) Bangkok, Hanoi, Jakarta.
        /// </summary>
        public static string SE_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("SE_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Kuala Lumpur, Singapore.
        /// </summary>
        public static string Singapore_Standard_Time {
            get {
                return ResourceManager.GetString("Singapore_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Harare, Pretoria.
        /// </summary>
        public static string South_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("South_Africa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:30) Sri Jayawardenepura.
        /// </summary>
        public static string Sri_Lanka_Standard_Time {
            get {
                return ResourceManager.GetString("Sri_Lanka_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Damascus.
        /// </summary>
        public static string Syria_Standard_Time {
            get {
                return ResourceManager.GetString("Syria_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Taipei.
        /// </summary>
        public static string Taipei_Standard_Time {
            get {
                return ResourceManager.GetString("Taipei_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Hobart.
        /// </summary>
        public static string Tasmania_Standard_Time {
            get {
                return ResourceManager.GetString("Tasmania_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Osaka, Sapporo, Tokyo.
        /// </summary>
        public static string Tokyo_Standard_Time {
            get {
                return ResourceManager.GetString("Tokyo_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+13:00) Nuku&apos;alofa.
        /// </summary>
        public static string Tonga_Standard_Time {
            get {
                return ResourceManager.GetString("Tonga_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+02:00) Istanbul.
        /// </summary>
        public static string Turkey_Standard_Time {
            get {
                return ResourceManager.GetString("Turkey_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Ulaanbaatar.
        /// </summary>
        public static string Ulaanbaatar_Standard_Time {
            get {
                return ResourceManager.GetString("Ulaanbaatar_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-05:00) Indiana (East).
        /// </summary>
        public static string US_Eastern_Standard_Time {
            get {
                return ResourceManager.GetString("US_Eastern_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-07:00) Arizona.
        /// </summary>
        public static string US_Mountain_Standard_Time {
            get {
                return ResourceManager.GetString("US_Mountain_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC) Coordinated Universal Time.
        /// </summary>
        public static string UTC {
            get {
                return ResourceManager.GetString("UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-02:00) Coordinated Universal Time-02.
        /// </summary>
        public static string UTC02 {
            get {
                return ResourceManager.GetString("UTC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-11:00) Coordinated Universal Time-11.
        /// </summary>
        public static string UTC11 {
            get {
                return ResourceManager.GetString("UTC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+12:00) Coordinated Universal Time+12.
        /// </summary>
        public static string UTC12 {
            get {
                return ResourceManager.GetString("UTC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC-04:30) Caracas.
        /// </summary>
        public static string Venezuela_Standard_Time {
            get {
                return ResourceManager.GetString("Venezuela_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Vladivostok, Magadan (RTZ 9).
        /// </summary>
        public static string Vladivostok_Standard_Time {
            get {
                return ResourceManager.GetString("Vladivostok_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+08:00) Perth.
        /// </summary>
        public static string W_Australia_Standard_Time {
            get {
                return ResourceManager.GetString("W_Australia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) West Central Africa.
        /// </summary>
        public static string W_Central_Africa_Standard_Time {
            get {
                return ResourceManager.GetString("W_Central_Africa_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
        /// </summary>
        public static string W_Europe_Standard_Time {
            get {
                return ResourceManager.GetString("W_Europe_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+05:00) Ashgabat, Tashkent.
        /// </summary>
        public static string West_Asia_Standard_Time {
            get {
                return ResourceManager.GetString("West_Asia_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+10:00) Guam, Port Moresby.
        /// </summary>
        public static string West_Pacific_Standard_Time {
            get {
                return ResourceManager.GetString("West_Pacific_Standard_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (UTC+09:00) Yakutsk (RTZ 8).
        /// </summary>
        public static string Yakutsk_Standard_Time {
            get {
                return ResourceManager.GetString("Yakutsk_Standard_Time", resourceCulture);
            }
        }
    }
}
