// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ST.WinIot.App
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IApiContract : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IDefaultModel.
        /// </summary>
        IDefaultModel DefaultModel { get; }

        /// <summary>
        /// Gets the IIdentity.
        /// </summary>
        IIdentity Identity { get; }

        /// <summary>
        /// Gets the ISmartHome.
        /// </summary>
        ISmartHome SmartHome { get; }

        /// <summary>
        /// Gets the IDevices.
        /// </summary>
        IDevices Devices { get; }

        /// <summary>
        /// Gets the IDeviceTraits.
        /// </summary>
        IDeviceTraits DeviceTraits { get; }

        /// <summary>
        /// Gets the IDeviceTypes.
        /// </summary>
        IDeviceTypes DeviceTypes { get; }

        /// <summary>
        /// Gets the IHomes.
        /// </summary>
        IHomes Homes { get; }

        /// <summary>
        /// Gets the IHubs.
        /// </summary>
        IHubs Hubs { get; }

        /// <summary>
        /// Gets the IPieces.
        /// </summary>
        IPieces Pieces { get; }

        /// <summary>
        /// Gets the IRelays.
        /// </summary>
        IRelays Relays { get; }

    }
}
