// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ST.WinIot.App.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DeviceNickName
    {
        /// <summary>
        /// Initializes a new instance of the DeviceNickName class.
        /// </summary>
        public DeviceNickName() { }

        /// <summary>
        /// Initializes a new instance of the DeviceNickName class.
        /// </summary>
        public DeviceNickName(string deviceNickNameId, string deviceId, string nickName = default(string))
        {
            DeviceNickNameId = deviceNickNameId;
            DeviceId = deviceId;
            NickName = nickName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceNickNameId")]
        public string DeviceNickNameId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceId")]
        public string DeviceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nickName")]
        public string NickName { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (DeviceNickNameId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DeviceNickNameId");
            }
            if (DeviceId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DeviceId");
            }
        }
    }
}
