// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ST.WinIot.App.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GoogleRequest
    {
        /// <summary>
        /// Initializes a new instance of the GoogleRequest class.
        /// </summary>
        public GoogleRequest() { }

        /// <summary>
        /// Initializes a new instance of the GoogleRequest class.
        /// </summary>
        public GoogleRequest(IList<Input> inputs = default(IList<Input>), string requestId = default(string))
        {
            Inputs = inputs;
            RequestId = requestId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inputs")]
        public IList<Input> Inputs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public string RequestId { get; set; }

    }
}
