// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ST.WinIot.App.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Hub
    {
        /// <summary>
        /// Initializes a new instance of the Hub class.
        /// </summary>
        public Hub() { }

        /// <summary>
        /// Initializes a new instance of the Hub class.
        /// </summary>
        public Hub(string hubId, string userId, string homeId, string pieceId, string hardware = default(string), Piece piece = default(Piece), IList<Device> devices = default(IList<Device>), IList<Relay> relays = default(IList<Relay>))
        {
            HubId = hubId;
            UserId = userId;
            HomeId = homeId;
            Hardware = hardware;
            PieceId = pieceId;
            Piece = piece;
            Devices = devices;
            Relays = relays;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubId")]
        public string HubId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "homeId")]
        public string HomeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hardware")]
        public string Hardware { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pieceId")]
        public string PieceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "piece")]
        public Piece Piece { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "devices")]
        public IList<Device> Devices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relays")]
        public IList<Relay> Relays { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (HubId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "HubId");
            }
            if (UserId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserId");
            }
            if (HomeId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "HomeId");
            }
            if (PieceId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PieceId");
            }
            if (this.UserId != null)
            {
                if (this.UserId.Length < 1)
                {
                    throw new ValidationException(ValidationRules.MinLength, "UserId", 1);
                }
            }
            if (this.Piece != null)
            {
                this.Piece.Validate();
            }
            if (this.Devices != null)
            {
                foreach (var element in this.Devices)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.Relays != null)
            {
                foreach (var element1 in this.Relays)
                {
                    if (element1 != null)
                    {
                        element1.Validate();
                    }
                }
            }
        }
    }
}
