// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ST.WinIot.App.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Input
    {
        /// <summary>
        /// Initializes a new instance of the Input class.
        /// </summary>
        public Input() { }

        /// <summary>
        /// Initializes a new instance of the Input class.
        /// </summary>
        public Input(string intent = default(string), object payload = default(object))
        {
            Intent = intent;
            Payload = payload;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intent")]
        public string Intent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payload")]
        public object Payload { get; set; }

    }
}
