

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http'; 
import { Observable } from 'rxjs/Rx'
import { IApiError } from "./IApiError"

//ST.Web.API
import { Device } from '../classes/Device';
import { GlobalService } from "../../global.service";
//Remote Call
@Injectable()
export class DevicesService {
    constructor(private _httpClient: HttpClient, private global: GlobalService) { }        
    
    // get: Manage/Devices      
    getDevices(): Observable<Device[]> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Devices`;
            return this._httpClient.get<Device[]>(_Url)
                .catch(this.handleError);
    }
    
    // get: Manage/Devices/${encodeURIComponent(id)}      
    getDevice(id: string): Observable<Device> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Devices/${encodeURIComponent(id)}`;
            return this._httpClient.get<Device>(_Url)
                .catch(this.handleError);
    }
    
    // put: Manage/Devices/${encodeURIComponent(id)}      
    putDevice(id: string, device: Device): Observable<void> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Devices/${encodeURIComponent(id)}`;
            return this._httpClient.put<void>(_Url, device)
                .catch(this.handleError);
    }
    
    // post: Manage/Devices      
    postDevice(device: Device): Observable<Device> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Devices`;
            return this._httpClient.post<Device>(_Url, device)
                .catch(this.handleError);
    }
    
    // delete: Manage/Devices/${encodeURIComponent(id)}      
    deleteDevice(id: string): Observable<Device> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Devices/${encodeURIComponent(id)}`;
            return this._httpClient.delete<Device>(_Url)
                .catch(this.handleError);
    }
    
    // Utility
    private handleError(error: HttpErrorResponse) {
        console.error(error);
        let customError: string = "";
        if (error.error) {
            customError = error.status === 400 ? error.error : error.statusText
        }
        let apiError: IApiError = {
            customText: customError || 'Server error',
            httpError: error
        }
        return Observable.throw(apiError);
    }
}
