

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http'; 
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
//ST.Web.API
import { DeviceTrait } from '../classes/DeviceTrait';
import { GlobalService } from "../../global.service";
//Remote Call
@Injectable()
export class DeviceTraitsService {
    constructor(private _httpClient: HttpClient, private global: GlobalService) { }        
    
    // get: Manage/DeviceTraits      
    getDeviceTraits(): Observable<DeviceTrait[]> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/DeviceTraits`;
            return this._httpClient.get<DeviceTrait[]>(_Url)
                .catch(this.handleError);
    }
    
    // Utility
    private handleError(error: HttpErrorResponse) {
        console.error(error);
        let customError: string = "";
        if (error.error) {
            customError = error.status === 400 ? error.error : error.statusText
        }
        return Observable.throw(customError || 'Server error');
    }
}
