

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http'; 
import { Observable } from 'rxjs/Rx'
import { IApiError } from "./IApiError"

//ST.Web.API
import { Hub } from '../classes/Hub';
import { GlobalService } from "../../global.service";
//Remote Call
@Injectable()
export class HubsService {
    constructor(private _httpClient: HttpClient, private global: GlobalService) { }        
    
    // get: Manage/Hubs      
    getHubs(): Observable<Hub[]> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Hubs`;
            return this._httpClient.get<Hub[]>(_Url)
                .catch(this.handleError);
    }
    
    // get: Manage/Hubs/${encodeURIComponent(id)}      
    getHub(id: string): Observable<Hub> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Hubs/${encodeURIComponent(id)}`;
            return this._httpClient.get<Hub>(_Url)
                .catch(this.handleError);
    }
    
    // put: Manage/Hubs/${encodeURIComponent(id)}      
    putHub(id: string, hub: Hub): Observable<void> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Hubs/${encodeURIComponent(id)}`;
            return this._httpClient.put<void>(_Url, hub)
                .catch(this.handleError);
    }
    
    // post: Manage/Hubs      
    postHub(hub: Hub): Observable<Hub> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Hubs`;
            return this._httpClient.post<Hub>(_Url, hub)
                .catch(this.handleError);
    }
    
    // delete: Manage/Hubs/${encodeURIComponent(id)}      
    deleteHub(id: string): Observable<Hub> {
        var _Url = this.global.ApiConfig.apiServer + `/Manage/Hubs/${encodeURIComponent(id)}`;
            return this._httpClient.delete<Hub>(_Url)
                .catch(this.handleError);
    }
    
    // Utility
    private handleError(error: HttpErrorResponse) {
        console.error(error);
        let customError: string = "";
        if (error.error) {
            customError = error.status === 400 ? error.error : error.statusText
        }
        let apiError: IApiError = {
            customText: customError || 'Server error',
            httpError: error
        }
        return Observable.throw(apiError);
    }
}
